module.exports = {
    ERROR: {
        SOMETHING_WENT_WRONG: 'Something Went Wrong.',
        LOGIN_FAILED: 'Login failed. Please retry again.',
        NO_ACCESS_EMAIL: 'Email Has No Access to Login.',
        USER_EXITS: 'User Already Exits.',
        USER_NOT_EXITS: "User Doesn't Exits.",
        INVALID_CREDENTIAL: 'Invalid Credential.',
        ENTER_NEW_PASSWORD: 'Please Enter New Pasword.',
        INVALID_ID: 'Not a Valid Id.',
        INVALID_USERID: 'Not a Valid User Id.',
        INVALID_ITEMID: 'Not a Valid Item Id.',
        INVALID_RATINGID: 'Not a valid Rating Id',
        INVALID_VOTE: 'Not a Valid Vote, Please Send UP/DOWN.',
        VERIFIED_USER: 'User Already Verified.',
        NO_UPDATE: 'Not Updated Anything Please Enter new Detais.',
        ITEM_EXITS_IN_CART: 'Item Already Exits in the Cart.',
        ITEM_EXITS_IN_FAVORITE: 'Item Already Exits in the Wish List.',
        CANNOT_DELETE_CART_ITEM: "Can't delete Cart Item",
        CANNOT_DELETE_FAVORITE_ITEM: "Can't delete Favorite Item",
        QUANTITY_SHOULD_GREATRER_THEN_ONE: 'Item Quantity Should Greater Then 1',
        CANNOT_INSERT_IN_RECENT_VIEW: "Can't Insert Item In Recently View",
        CANNOT_DELETE_RECENT_VIEW_item: "Can't delete from Recent View Item",
        NOT_AVAILABLE_SPECIFICATION: "Not Available Item for this Specification",
        ALREADY_LIKED_REVIEW: 'Already You Have Liked this Review.',
        ALREADY_DISLIKED_REVIEW: 'Already You Have Disliked this Review.',
        ALREADY_DISLIKED_QUESTION: 'Already You Have Disliked this Question.',
        ALREADY_LIKED_QUESTION: 'Already You Have Liked this Question.',
    },
    SUCCESS: {
        ACCOUNT_CREATED: 'Account Created Successfully.',
        LOGIN_SUCCESSFULL: 'Login Successfully.',
        VERIFIED_SUCCESSFULL: 'Account Verified Successfully.',
        USER_DATA_FETCHED: 'User Data Fetched Successfully.',
        PASSWORD_UPDATED: 'Password Updated Successfully.',
        PROFILE_UPDATED: 'Profile Updated Sccessfully.',
        ITEM_ADDED_IN_CART: 'Item Added Successfully in the Cart.',
        ITEM_ADDED_IN_FAVORITE: 'Item Added Successfully in the Wish List.',
        CART_ITEMS_FETCHED: 'Cart Items Fetched Successfully.',
        CART_FAVORITE_FETCHED: 'Wish List Items Fetched Successfully.',
        CART_ITEM_DELETED: 'Cart Item Deleted Successfully.',
        FAVORITE_ITEM_DELETED: 'FAVORITE Item Deleted Successfully.',
        QUANTITY_UPDATED: 'Item Quantity Updated Successfully.',
        ITEM_ADDED_IN_RECENT_VIEW: "Item Added Successfully in the Recently View.",
        HOME_DETAILS_FETCHED: 'Home Deatils Fetched Successfully.',
        ITEMS_FETCHED: 'Product fetched successfully',
        ITEM_FETCHED: 'Item details fetched successfully',
        ITEM_REVIEW_UPDATED: "Item Review Updated successfully",
        QUESTION_SUBMITTED: "Question Submitted Successfully",
        REVIEW_VOTE_UPDATED: 'Item Review Vote Updated successfully',
        QUESTION_VOTE_UPDATED: 'Item Question Vote Updated successfully',
    }
};