import './globals.css'
import Footer from '@/components/Footer'
import Header from '@/components/Header'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import * as React from "react";
import { Alert } from "@mui/material";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <main className='flex flex-col min-h-screen'>
          <Header />
          <div id="alert-message" className='absolute top-[5px] left-[60px] z-[1000] w-full flex justify-center'></div>
          <section className='flex-1 flex flex-col'>{children}</section>
          <Footer />
        </main>
      </body>
    </html>
  )
}
