export const MESSAGE = {
    ERROR: {
        SOMETHING_WENT_WRONG: 'Something Went Wrong.',
        LOGIN_FAILED: 'Login Failed. Please Retry Again.',
        NO_ACCESS_EMAIL: 'Email Has No Access to Login.',
        USER_EXITS: 'User Already Exits.',
        INVALID_CREDENTIAL: 'Invalid Credential.',
        USER_NOT_EXITS: "User Doesn't Exists.",
        ENTER_NEW_PASSWORD: "Please Enter New Password.",
        LOGIN_FIRST: "Please Login First, You Don't Have Permission.",
        ENTER_NEW_DETAILS: "Not Updated Any Details.",
        QTY_GREATER_THEN_ONE: "Item Quantity Shoul Greater Then 1.",
        CANNOT_UPDATE_QTY: "Item Quantity Can't be Update.",
        WRITE_QUESTION: "Please Write Question.",
        WRITE_REVIEW: "Please Select Rating and Write Review.",
    },
    SUCCESS: {
        ACCOUNT_CREATED: 'Account Created Successfully.',
        LOGIN_SUCCESSFULL: 'Login Successfully.',
        LOGOUT_SUCCESSFULL: 'Log-out Successfully.',
        VERIFY_SUCCESSFULL: 'Verified Successfully.',
        PASSWORD_UPDATED: 'Password Updated Successfully.',
        PROFILE_UPDATED: "Profile Updated Successfully.",
        ITEM_DELETED: "Item Deleted Successfully.",
        FAVORITE_ITEM_DELETED: "Item Deleted from Wish List Successfully.",
        CART_QTY_UPDATED: "Quantity Updated Successfully.",
        ADDED_FAVORITE_ITEM: "Item Added in the Wish List Successfully.",
        ADDED_CART_ITEM: "Item Added in the Cart Successfully.",
        REVIEW_SUBMITTED: "Item Review Submitted Successfully.",
        QUESTION_SUBMITTED: "Question Submitted Successfully.",
        REVIEW_VOTE_SUBMITTED: "Item Review Vote Updated successfully",
        QUESTION_VOTE_SUBMITTED: "Item Question Vote Updated successfully",
    },
    WARNING: {
        ALREADY_ADDED_IN_CART: "Item Already Exits in the Cart.",
        ALREADY_ADDED_IN_WISH_LIST: "Item Already Exits in the Wish List.",
    }
}